### ISSUE TITLE
Analytics submission

### ISSUE THREAD

**Issue by Gerzer** [wtg/Shuttle-Tracker-Server#17]
We need to implement the ability to receive and to store submissions of analytics data from the various frontends.

**Comment by mahi-pas** [comment]
I will be doing the JSON structure for board bus messages

**Comment by mahi-pas** [comment]
Attached is a document detailing my plans for data that will be tracked:
[Analytics Blueprint](https://docs.google.com/document/d/1fPYbemSem0jyjARmP1f_-OFf8ygnclxX1s0tsAg0gEs/edit?usp=sharing)

Let me know if it is missing anything, or if anything could be implemented more efficiently than what I proposed.

**Comment by mahi-pas** [comment]
Attached in a document detailing sample JSON submissions from various frontends:
[Analytics JSON](https://docs.google.com/document/d/1SEF9Xt4keHo5Tf5Zy99QhsIYF3lD7z4PwLg7eZoHdAU/edit?usp=sharing)

Let me know if there are any problems or if anything can be implemented better

**Comment by mahi-pas** [comment]
Attached is a document detailing how I will handle date server side
[Analytics: Server-side Handling](https://docs.google.com/document/d/1wyaDWdDawTB-A_AH0PsizAaZ4cDAjgV0iYDRSpuifyM/edit?usp=sharing)

Let me know if there are any problems or if anything can be implemented better

**Comment by mahi-pas** [comment]
Documents have now been moved to the wiki page. You can find it all here:
[https://github.com/wtg/Shuttle-Tracker-Server/wiki/Analytics](https://github.com/wtg/Shuttle-Tracker-Server/wiki/Analytics)
